- README.md
- lib/src/docker/run_image.dart
- lib/src/util/print_usage.dart
- tool/template.dart
Make the Port variable for the run command
Usage: -p, --port 
defaults to `localhost:8000`
> Make port variable

- lib/src/docker/stop_image.dart
Use kill instead of stop to be faster
> Use kill instead of stop

- lib/src/docker/run_image.dart
- lib/src/docker/stop_image.dart
- lib/src/util/command_runner.dart
Now killing the Container before running
> Kill before run

- tool/template.dart
This is useful when running the server on the dart VM for debugging
> Print url when server has been started

- README.md
- lib/dockerize_sidekick_plugin.dart
- lib/src/util/hash_scripts.dart
- pubspec.yaml
- template/build_command.template.dart
- template/middlewares.template.dart
- template/server.template.dart
- test/helper/load_html.dart
- test/test_resources/sample.html
- test/test_resources/sample_with_nonce.html
- test/util/hash_scripts_test.dart
This PR is addressing Issue #25 
We are now able to generate working hashes for each script in the `index.html` at build time
> Add hash and nonces

- lib/src/docker/run_image.dart
- template/run_command.template.dart
- template/server.template.dart
Now we are exposing the right ports and be able to set the right ports to run on any port we want locally
Fixed #41
> Be able to use other ports

- lib/src/util/hash_scripts.dart
- template/README.template.md
- template/pubspec.template.yaml
- template/server.template.dart
- tool/create_server_folder.dart
- Added a readme to the server folder
- sorted pub dependencies
- Added `runs-locally` to server file to be able to switch between docker and pure dart execution
- Removed unused print
> Add readme to server

- lib/src/docker/run_image.dart
- template/run_command.template.dart
Moved the stopImage function call into the command so that it is easier to remove it if the user dont want this behaviour
> Move stop function call in run-command

- README.md
- lib/dockerize_sidekick_plugin.dart
- lib/src/docker/create_image.dart
- lib/src/docker/run_image.dart
- lib/src/docker/stop_image.dart
- lib/src/util/enforce_csp.dart
- template/build_command.template.dart
- template/environment.template.dart
- template/middlewares.template.dart
- template/run_command.template.dart
- template/server.template.dart
- tool/install.dart
Added environments.
Did the following:
- Added a environment class with default values
- Added environments to `build` and `run` command.
- Enforcing CSP Rules if User is building in prod mode
> Add environment

- README.md
Added links to how to deploy to Google Cloud Run, AWS and Azure 
Resolves #31
> Add links deploy to different services

- lib/src/docker/run_image.dart
Added a comment which is printed while running the app. To remember the user to press `ctrl+c` twice
> Add comment while running to press ctrl+c twice

- CHANGELOG.md
- pubspec.yaml
> Bump version

- CHANGELOG.md
- pubspec.yaml
- template/middlewares.template.dart
Fixed a bug where CSPs where unintentionally enforced
Bumped version
> Fix CSP Bug & bump version

- lib/dockerize_sidekick_plugin.dart
- lib/src/util/hash_scripts.dart
- lib/src/util/version_file.dart
- template/build_command.template.dart
- tool/create_server_folder.dart
- tool/install.dart
Added a version file to our build so that you can access it via 
`localhost:8000/version.json` to quickly check if you are running the right version and environment.
Adressing #61
> Add version file

- README.md
Removing sidekick_plugin, because its kinda weird to read
> Make readme title more appealing

- README.md
- lib/dockerize_sidekick_plugin.dart
- lib/src/docker/run_image.dart
- lib/src/util/is_port_valid.dart
- template/run_command.template.dart
This PR solves #68  and is some kind of prework of #54 
Now you are able to press `Ctrl-C` just once to exit and kill the container
> Kill with ctrl c once

- lib/src/docker/create_image.dart
- lib/src/docker/run_image.dart
- lib/src/util/move_to_server_directory.dart
- pubspec.yaml
- template/run_command.template.dart
This PR is solving #54 
Implemented a hot-rebuild with a file watcher.
Rebuilding Flutter App and Docker Container if a change was detected in the files
Rebuilding only the Docker Container if a change was detected in the Server Folder
> Hot rebuild

- lib/src/docker/create_image.dart
- lib/src/docker/run_image.dart
- lib/src/docker/stop_image.dart
- lib/src/util/check_docker_install.dart
- lib/src/util/command_runner.dart
- lib/src/util/hash_scripts.dart
- lib/src/util/is_port_valid.dart
- pubspec.yaml
- template/build_command.template.dart
- template/run_command.template.dart
Improved the logger for better outputs and less noise.
Adressing #70
> Improve logger

- README.md
- lib/src/docker/create_image.dart
- lib/src/docker/run_image.dart
- lib/src/util/command_runner.dart
- lib/src/util/print_usage.dart
- template/Dockerfile.template
- template/build_app_command.template.dart
- template/build_command.template.dart
- template/build_image_command.template.dart
- template/build_scripts_command.template.dart
- template/docker_command.template.dart
- template/run_command.template.dart
- test/util/print_usage_test.dart
- tool/create_server_folder.dart
- tool/install.dart
This is the first step of refactoring our build logic
**Merging to main will break the run command**
> Refactor build

- lib/src/docker/run_image.dart
- Removed one debug print
- Fixed bug that hot reload was inverted
> Hot Fix reload

- .github/workflows/on_push.yml
- lib/src/util/hash_scripts.dart
- template/build_scripts_command.template.dart
- test/helper/load_html.dart
- test/test_resources/sample_with_empty_scripts.html
- test/test_resources/sample_with_no_scripts.html
- test/util/hash_scripts_test.dart
- Added tests for the hash_scripts file
- Bumped min Coverage to 38
> Add more tests

- README.md
- lib/src/docker/create_image.dart
- lib/src/docker/run_image.dart
- lib/src/util/move_to_server_directory.dart
- pubspec.yaml
- template/build_image_command.template.dart
- template/build_scripts_command.template.dart
- template/docker_command.template.dart
- template/pubspec.yaml
- template/run_command.template.dart
- template/stop_command.template.dart
- tool/create_server_folder.dart
- tool/install.dart
Bumped the Sidekick Core version to 1.0.0
Bumped Sidekick Plugin Installer to 0.3.0
Bumped minDartSDK to 2.16.0
Migrated deprecated members
Fixed print bug
> Bump sidekick core

- CHANGELOG.md
- README.md
- lib/src/util/print_usage.dart
- pubspec.yaml
- test/util/print_usage_test.dart
Bumping the version for the upcoming 0.3.0 release
> Bump Version to 0.3.0

- lib/src/docker/create_image.dart
- template/Dockerfile.template
- template/build_scripts_command.template.dart
- template/main.template.dart
- template/pubspec.yaml
- template/server.template.dart
- tool/create_server_folder.dart
- tool/install.dart
- tool/replace_template_dependencies.dart
Refactored our server folder to be able to have the bin/ folder for a main method and our server and middlewares separated in the `lib/src` folder
> Refactor server

- CHANGELOG.md
- pubspec.yaml
> Bump version to 0.4.0

- CHANGELOG.md
- lib/dockerize_sidekick_plugin.dart
- lib/src/data/dockerize_data.dart
- pubspec.yaml
Adding dockerize data object
Will be merged after #97 
To make dockerize ready for the registrant build update
> Add dockerize Data

- CHANGELOG.md
- pubspec.yaml
> Bump to version 0.6.0

- lib/dockerize_sidekick_plugin.dart
- pubspec.yaml
Please let me know if you're fine with this, then i update the CI to also use 3.0.0
> Update dependencies to sdk >= 3.0.0
